Edit & delete log functionality
GTBitsOfGood/canine-assistants pull request #114
Opened 2024-01-29 20:12 UTC by ShmulTomer

## PR Title

Issue Number(s): #85
What does this PR change and why?

Delete functionality [almost complete]
- make sure only the user that created the log can delete

Edit functionality [to do]

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-a841a38d02db4428a7cdc85dcbb8a35c?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related PRs

PR Number(s): #number_of_pr

### How To Test

The steps to test the functionality of your ticket. Include edge cases and testing of error handling, if applicable.

2024-01-30 16:56 UTC, afazio1 requested changes
Awesome work! Thanks for getting this out so quick. 

Some things I found:
- fetching log info for the edit modal sometimes takes too long, which leaves the modal blank and can be confusing for the user. (see comment in code)
- when editing a log, the first time you click on any dropdown, the dropdown will not be populated with state of the currently selected values
- I found an issue on the deploy preview (but not locally for some reason) where a toast kept appearing when clicking a specific button on one of the modals, but I changed the button to `type=button` and it resolved the issue

2024-01-30 16:56 UTC, afazio1 commented on src/components/Log/LogModal.jsx
> +      fetch("/api/logs/" + logId)
if you pass in the entire `log` object instead of just `logId` as props to this component, you won't have to fetch the log again. Sometimes it takes too long for the log contents to populate in the modal, which leaves the fields blank and is confusing for the user. If you would rather rely on the server state, I would disable the inputs or indicate a loading state in some way (we can talk to design about this).

2024-01-30 16:57 UTC, afazio1 commented on src/components/Tab/TabContainer.jsx
> +  const handleEditSuccess = (success) => {
do we need this anymore? seems like the state updates properly

2024-01-30 17:02 UTC, afazio1 commented on src/components/Log/Log.jsx
> +      {isAuthor &&(
I would check the spacing on these icons and refer to the figma

2024-01-30 19:02 UTC, ShmulTomer commented
Changes:
- if the author of a log no longer exists in “user”, it gave an error -> now it just shows N/A for the author
- edit and delete spacing better matches the Figma
- passed in log so editing a log populates instantly
(remnant from the unfinished branch, thanks for pointing this out)
- populating the dropdown menu when clicked the first time (fixed by editing DropdownMenu itself, updating the enabled options whenever selectedOptions prop is changed)

2024-01-31 20:28 UTC, afazio1 approved these changes
Great work!

2024-02-03 17:47 UTC, laurenmcp commented
Looks great to me. Thanks for the good work Tomer!!

2024-02-03 17:48 UTC, laurenmcp approved these changes

2024-02-03 18:04 UTC, dograh commented
The edit and delete buttons look great! I just have a few minor changes. Can we remove the word "a" from the edit a log title and keep it as "Edit Log"? Can we also increase the spacing between the text and cancel/confirm buttons in the delete confirmation modal? Other than that it looks perfect. Thanks for your hard work!

2024-02-05 18:29 UTC, ShmulTomer commented
Made those changes! Thanks for reviewing

@afazio1 do you merge or do I?

2024-02-05 18:30 UTC, afazio1 commented
I will merge👍

2024-02-05 21:35 UTC, afazio1 approved these changes

2024-02-05 21:36 UTC, merged