added image upload button to dog forms
GTBitsOfGood/canine-assistants pull request #119
Opened 2024-02-03 00:19 UTC by madelinehartlage

## PR Title

Issue Number(s): #108

What does this PR change and why? PR adds image upload button to add-dog and edit-dog forms for the ability to add and manage profile pictures of dogs

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related PRs

PR Number(s): #107 

### How To Test

Click Add Dog on dashboard. Click Upload Image. A preview will appear. If an image is already available for the dog, a button for Replace Image and Delete will show.

2024-02-03 00:23 UTC, madelinehartlage commented
Upload buttons are added as best matching to the figma as possible. Delete button clears dog.image but uploading to Backblaze does not work and there is no propagation to the database.

2024-02-03 18:05 UTC, laurenmcp requested changes
Great work madeline! Two small things:
When I upload a portrait image the image overflows outside of the box. I think this can be fixed by updating the overflow properties to clip off excess (Similar to a cover in chakraui).
Also I'm not seeing the option to clear or update the image. This functionality looks like this in the figma: 
<img width="249" alt="image" src="https://github.com/GTBitsOfGood/canine-assistants/assets/111540842/4cd34913-36f6-414a-abb1-4b76674bc428">

2024-02-03 18:40 UTC, madelinehartlage commented
For my ticket, from my understanding, the delete and replace image buttons should only be visible when a dog already has an image and someone wants to update it. So I put the buttons there to be displayed when dog.image equals something. Currently the buttons won’t display because we can’t figure out the upload file functionality so a dog will never have an image but if I were to set an image for the dog somehow, then the buttons should display. Let me know if I’ve interpreted this wrong.

2024-02-04 04:01 UTC, afazio1 requested changes
Great work! Mentioned a few things in the comments. A lot of this depends on the backend ticket, so I may wait to merge this

2024-02-04 04:01 UTC, afazio1 commented on src/components/ImageUpload.jsx
> +  const upload = async () => {
How would we call this function on Save? I'm thinking it may have to be moved outside of this component

2024-02-04 04:01 UTC, afazio1 commented on src/components/ImageUpload.jsx
> +        {previewFile && <img src={previewFile.base64} />}
use Next's image component: https://nextjs.org/docs/pages/api-reference/components/image

2024-02-04 23:27 UTC, madelinehartlage commented
Could not figure out how to fix overflow issues but attempted to fix others. (convert to next image, display replace and delete buttons when any photo is in the box, pull out upload function). Also got backblaze to work.

2024-02-06 04:47 UTC, afazio1 approved these changes

2024-02-06 04:58 UTC, merged