implement signup/login logic for error handling
GTBitsOfGood/canine-assistants pull request #129
Opened 2024-02-13 22:16 UTC by emilyliublair

## Login/Signup Perms

Issue Number(s): #121 

creates logic for user login and sign up permissions

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

n/a

### Related PRs

PR Number(s): #128 

### How To Test

The steps to test the functionality of your ticket. Include edge cases and testing of error handling, if applicable.

2024-02-16 05:58 UTC, emilyliublair commented
didn't touch callback logic so user will always be directed to /dogs upon clicking login/signup regardless of error or not

2024-02-18 03:46 UTC, afazio1 requested changes
great work!! See comments for a few changes

2024-02-18 03:46 UTC, afazio1 commented on server/db/actions/User.js
> +export async function updateUser(email, password, name) {
make sure changing this functions args doesn't affect other routes that use `updateUser()`. If it does, you can add another function for the user signup use case instead of trying to combine them into 1 function

2024-02-18 03:46 UTC, afazio1 commented on src/pages/api/auth/[...nextauth].js
> +          return response;
this error doesn't appear on the frontend see https://stackoverflow.com/questions/76750792/nextauth-how-to-return-custom-errors-without-redirection

2024-02-18 03:46 UTC, afazio1 commented on src/pages/api/auth/[...nextauth].js
> +      console.log(message);
remove console.logs

2024-03-02 14:35 UTC, merged