Dog Access Level Information
GTBitsOfGood/canine-assistants pull request #130
Opened 2024-02-13 22:55 UTC by qad114

## Dog Access Level Information

Issue Number(s): #123

Adjusts the information returned to the user depending on their access level and association with the dog(s). 

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### How To Test

On the dashboard, ensure that only dogs associated with the user are displayed. Also ensure that, if a dog with a volunteer/partner association is clicked, then only limited information is displayed.

2024-02-18 02:42 UTC, afazio1 requested changes
Great work! See comments for a few minor changes

2024-02-18 02:42 UTC, afazio1 commented on src/pages/api/dogs/[id].js
> +      const token = await getToken({ req });
use `const session = await getServerSession(req, res, authOptions);` for consistency

2024-02-18 02:42 UTC, afazio1 commented on src/pages/api/dogs/[id].js
> +        user.role !== "Admin" &&
make sure `"Manager"`s can see all dogs as well

2024-02-18 21:28 UTC, laurenmcp reviewed
Nice job Hamza!! Looks great to me provided that alexa's requested changes are implemented.

2024-02-20 05:11 UTC, afazio1 approved these changes
Love it when it just works 👍 😎

2024-02-20 14:35 UTC, merged