Individual dog mobile views
GTBitsOfGood/canine-assistants pull request #141
Opened 2024-02-23 00:18 UTC by madelinehartlage

## Individual Dog Mobile Views

Issue Number(s): #136 

What does this PR change and why? Adds mobile views for individual dog page for mobile friendly application use. Creates mobile version of individual dog page, editing a dog, adding a log, viewing logs, adding a form, and viewing forms.

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

- None

### Related PRs

-None

### How To Test

Add a dog and view its individual page on mobile. Attempt editing the dog, adding and viewing logs, and adding and viewing forms.

2024-03-03 20:05 UTC, dograh commented
First of all, this looks fantastic! This ticket was massive, and you've done an awesome job taking it on! I have noticed a couple of things that need changes:

- Can we move the Edit Dog / Add a Log / Add a Form button up to have a little more space from the bottom of the screen?
- For the log tags, the Topic should be inline with the Severity tag and the Severity should go first. There should also be an overflow if there are more than 1 tag and the user can click on the number to see all additional tags. See the screenshot for reference:
<img width="274" alt="Screenshot 2024-03-03 at 2 22 06 PM" src="https://github.com/GTBitsOfGood/canine-assistants/assets/52293714/7c674340-fde7-48d2-98a2-fb9a13871474">
- The resolve, edit, and delete buttons should be inline above the tags
- Can we make the search input field extend the width of the navbar that is right above it?
- Can we make the Information / Logs / Forms tab centered on the screen instead of left-aligned?
- For the edit log modal, there is extra space at the bottom of the screen. Can we keep it fixed to the bottom of the screen and then extend it upwards if there needs to be extra space?
- The cancel button styling needs to be changed to the secondary colors (gray instead of white)
- For the forms dropdown menu, can we have the dropdown extend the same width as the "add a form" button that comes before it? I have just now added this to the Figma, apologies for it not being there before!

I'm not sure which of these are in the scope of your ticket, so feel free to ignore what doesn't apply to you. Thanks for all of your hard work!!

2024-03-05 00:46 UTC, laurenmcp requested changes
Great job madeline! Thanks for working so hard on this monster front end ticket. In addition to Hemadri's requests, I only noticed one thing to fix:
It seems the log filter by tag dropdown is cutoff, making some of the options and the apply button inaccessible. I think this was an issue fixed on another page, so @afazio1 may be able to guide to an easy solution.
<img width="705" alt="image" src="https://github.com/GTBitsOfGood/canine-assistants/assets/111540842/5d706b63-d82c-4249-8386-0340d64c8a3e">

2024-03-18 18:21 UTC, afazio1 commented
<img width="362" alt="Screenshot 2024-03-18 at 2 19 08 PM" src="https://github.com/GTBitsOfGood/canine-assistants/assets/45372449/07fdbdea-d97d-45f0-9bde-b78c7dd81ae4">
I don't see the mobile view for the the Information tab and the page breaks on dogs that do not have a values for placement date

2024-03-26 16:04 UTC, afazio1 approved these changes

2024-03-27 01:32 UTC, afazio1 approved these changes

2024-03-27 01:43 UTC, afazio1 approved these changes

2024-03-27 01:50 UTC, merged