Scaled dog images
GTBitsOfGood/canine-assistants pull request #177
Opened 2024-03-11 02:09 UTC by ShmulTomer

## PR Title

Issue Number(s): #153

What does this PR change and why?

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

None

### How To Test

The steps to test the functionality of your ticket. Include edge cases and testing of error handling, if applicable.

2024-03-18 18:52 UTC, afazio1 requested changes

2024-03-18 18:52 UTC, afazio1 commented on src/components/Dog/CardDogTable.jsx
> +        {dog.image ?
is there a reason you are using regular styles instead of tailwind? I would prefer you to use tailwind to keep consistency throughout the codebase

2024-03-25 16:32 UTC, dograh commented
Design looks good!

2024-03-28 04:36 UTC, afazio1 approved these changes

2024-03-28 04:40 UTC, merged