Create custom 404 and 500 error pages
GTBitsOfGood/canine-assistants pull request #188
Opened 2024-03-20 21:58 UTC by emilyliublair

## Create custom 404 and 500 error pages

Issue Number(s): #166 

What does this PR change and why?
Creates custom 404 and 500 error pages

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

### Related PRs

PR Number(s): 

### How To Test

route to /404 and /500 to see error pages

2024-03-24 13:35 UTC, afazio1 requested changes
Works great just a nit about using tailwind instead of `style`!!

2024-03-24 13:35 UTC, afazio1 commented on src/pages/404.js
> +      style={{
Can we use tailwind here for consistency?

2024-03-24 19:56 UTC, laurenmcp approved these changes
looks great emily! approved provided that alexa's small nit is fixed

2024-03-25 16:11 UTC, dograh commented
Yayyy they look great! Awesome job!! Something to keep in mind though is that there are some spacing concerns when adjusting for screen size. When zooming in, the image starts to overlap outside of the white box. Not sure if that's a part of the ticket or not, but just wanted to point that out! Other than that it looks so good!!

2024-03-26 12:52 UTC, afazio1 approved these changes

2024-03-26 15:09 UTC, merged