Tomer 173 edit delete
GTBitsOfGood/canine-assistants pull request #195
Opened 2024-03-25 19:42 UTC by ShmulTomer

## PR Title

Issue Number(s): #number_of_issue

What does this PR change and why?

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related PRs

PR Number(s): #number_of_pr

### How To Test

The steps to test the functionality of your ticket. Include edge cases and testing of error handling, if applicable.

2024-03-26 15:54 UTC, afazio1 requested changes
Good work just a few questions and small fixes

2024-03-26 15:54 UTC, afazio1 commented on src/pages/dogs/[id]/index.jsx
> +                  {(userRole === "Admin" || userRole === "Manager" || userRole === "Instructor/Caregiver") &&
I don't think there is a role for "Instructor/Caregiver" unless then endpoint was changed. What you can do is check if `dog.association != "Volunteer/Partner"`. If that is the case, we know the user must be a Admin, Manager, or have association Instructor/Caregiver

2024-03-26 15:54 UTC, afazio1 commented on src/pages/dogs/[id]/index.jsx
> +    console.log(data)
remove

2024-03-26 15:54 UTC, afazio1 commented on src/pages/dogs/index.jsx
> +      .then((data) => { console.log(data); setData(data); setLoading(false); } );
remove console.log

2024-04-08 18:50 UTC, laurenmcp requested changes
Permissions for Instructor/Caregiver look great, but the delete button is still deactivated for Managers/Admin. Thanks for the good work!!

2024-04-09 03:20 UTC, ShmulTomer commented
@laurenmcp oops, made the change!

2024-04-09 12:45 UTC, laurenmcp approved these changes
awesome, thanks for the change!

2024-05-03 17:50 UTC, afazio1 commented
#244

2024-05-03 17:50 UTC, closed without merging