Server-side Pagination
GTBitsOfGood/canine-assistants pull request #232
Opened 2024-04-06 08:13 UTC by emilyliublair

## Server-side Pagination

Issue Number(s): #189 

What does this PR change and why?
implements serverside pagination

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related PRs

PR Number(s): #number_of_pr

### How To Test

check to see that only certain number of data is returned rather than all

2024-04-08 12:13 UTC, dograh commented
Design looks good! Great work!

2024-04-09 12:40 UTC, laurenmcp reviewed
Looks awesome emily! 
One thing- there seems to be a client side error on the Access management page. Could you investigate this? I'm thinking the access management table may have a dependency on the table component, but Alexa will be able to provide more guidance on why this may be happening.

2024-04-09 20:57 UTC, afazio1 requested changes
Looks awesome!! 

A few things:
- When there are 0 logs / dogs, pagination should be clamped. But I am able to click it and get NaN
<img width="1214" alt="Screenshot 2024-04-09 at 4 47 43 PM" src="https://github.com/GTBitsOfGood/canine-assistants/assets/45372449/8650673b-c2b0-4438-b57b-593bda4d27fd">

2024-04-09 20:57 UTC, afazio1 commented on src/components/Table/Table.jsx
>      <div className="flex bg-white justify-between items-center px-6 py-4 w-[90vw] sm:w-full mt-2 sm:mt-0 rounded-lg sm:rounded-none border-gray-300 border-[1px] sm:border-0">
change `w-[90vw]` to `w-full`

2024-04-21 06:08 UTC, afazio1 approved these changes

2024-04-21 06:08 UTC, merged