Update and Delete Form API endpoints
GTBitsOfGood/canine-assistants pull request #83
Opened 2023-10-28 18:11 UTC by jaipise

## Update and Delete Form API endpoints
Issue Number(s): #57 

What does this PR change and why?
### Checklist
- [x] Requirements have been implemented
- [x] Acceptance criteria is met
- [x] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-a841a38d02db4428a7cdc85dcbb8a35c?pvs=4) have been updated or are not necessary
- [x] Code follows design and style guidelines
- [x] Commits follow guidelines (concise, squashed, etc)
- [x] Relevant reviewers (EM) have been assigned to this PR

### How To Test
The steps to test the functionality of your ticket. Include edge cases and testing of error handling, if applicable.

2023-10-29 21:21 UTC, afazio1 requested changes
great work! Just one minor error handling thing

2023-10-29 21:21 UTC, afazio1 commented on server/db/actions/Form.js
> +    if (!deletedForm) {
this is caught in the `catch` and the message gets overridden

2023-10-29 21:22 UTC, afazio1 requested changes

2023-10-29 21:22 UTC, afazio1 commented on server/db/actions/Form.js
> +    throw new Error("Unable to update form");
this is caught in the `catch` and the message gets overridden

2023-10-29 21:26 UTC, afazio1 requested changes

2023-10-29 21:26 UTC, afazio1 commented on server/db/actions/Form.js
> +      throw new Error("Invalid form ID");
this is error is caught in the `catch` and the message is overridden

2023-10-31 15:48 UTC, afazio1 approved these changes

2023-10-31 15:56 UTC, afazio1 requested changes
found a small thing with response shape

2023-10-31 15:56 UTC, afazio1 commented on src/pages/api/forms/[id].js
> +          error: error.message,
there shouldn't be `error` key here

2023-10-31 17:18 UTC, jaipise commented
> found a small thing with response shape

Yep sorry, not sure why I added that

2023-10-31 17:48 UTC, afazio1 approved these changes

2023-10-31 17:48 UTC, merged